### ISSUE TITLE
(Issue) Alumni Status

### ISSUE THREAD

**Issue by Beanow** [tauri-apps/governance-and-guidance#41]
Initial Discord discussion: https://discord.com/channels/616186924390023171/1146650713271828540
Draft document: https://hackmd.io/@jacobbolda/SkRuFYap3

**Comment by christianlessard** [comment]
Discussion is being moved to this issue: #43 

Note: I incorporated the language of the draft document into [Updating GOVERNANCE.MD](https://hackmd.io/f-V_NUB5TR-62j1hnwgu8A)
