### ISSUE TITLE
Get in touch with Commons Concervancy

### ISSUE THREAD

**Issue by Beanow** [tauri-apps/governance-and-guidance#6]
https://commonsconservancy.org/

They may be able to help us create a foundation for Tauri.

**Comment by nothingismagick** [comment]
Yeah, we talked about this already in DM, its a good idea to track it here.

**Comment by Beanow** [comment]
Well, our Programme will celebrate it's 2 year birthday soon, I think we can close this issue :laughing:
https://dracc.commonsconservancy.org/0035/
